spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-dept  #微服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  #mysql驱动包（org.gjt.mm.mysql.Driver）
    url: jdbc:mysql:///clouddb01?characterEncoding=utf8  #数据库名称
    username: root
    password:
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路劲
  type-aliases-package: com.dongren.pojo #所有pojo别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #mapper映射文件

eureka:
 client:
   service-url:
    defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #客户端注册进eureka服务列表中
 instance:
   instance-id: springcloud-dept-8001 #自定义服务名称信息
   prefer-ip-address: true  #访问路径可以显示IP地址
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: springcloud-dept  #微服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  #mysql驱动包（org.gjt.mm.mysql.Driver）
    url: jdbc:mysql:///clouddb01?characterEncoding=utf8  #数据库名称
    username: root
    password:
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路劲
  type-aliases-package: com.dongren.pojo #所有pojo别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #mapper映射文件

eureka:
 client:
   service-url:
    defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #客户端注册进eureka服务列表中
 instance:
   instance-id: springcloud-dept-8001 #自定义服务名称信息
   prefer-ip-address: true  #访问路径可以显示IP地址